### ISSUE TITLE
where is tmp in Fig_1.R?

### ISSUE THREAD

**Issue by liamxg** [genomicsurveillance/Genomic_epidemiology_reveals_how_restriction_measures_shaped_the_SARS-CoV-2_epidemic_in_Brazil#1]
Error in ggplot(data = tmp) : object 'tmp' not found

**Comment by koppk** [comment]
Dear genomicsurveillance, Dear Vagner Fonseca, Dear LiXingguangBrandonStark 

I have the same problem. 

This is the message:

g<- ggplot(data=tmp) +  ggstyleTILE +
  geom_hline(yintercept=0, color='black', size=0.3) +
  geom_hline(yintercept=1, color="#009176", linetype=2) +
  geom_segment(data=phases, aes(x=start, y=y, xend=end, yend=y, col=lab), size=5) 
  scale_color_manual("",values=collevels, labels=phases$lab)  +
  new_scale_color()+
  geom_bar(aes(x=date, y=cases), stat ="identity", size=0.6, color="grey44") +
  geom_line(aes(x=date, y=deaths*f), size=0.6, color="red") +
  scale_y_continuous(sec.axis = sec_axis(~./f, name = "deaths")) +
  ggtitle("SARS-CoV-2 epidemic in Brazil") + ylab("cases") + xlab("month") +
  theme(legend.position=c(0.65,0.7),legend.text= element_text(size=12, family="Helvetica")) +
  scale_shape_manual("", values='_', labels="Level 5") +
  scale_x_date(labels = date_format("%b-%y"), date_breaks = "1 month") +
  geom_rug(data= data2, aes(x=days),color='dodgerblue3',alpha=0.2,outside =FALSE,length = unit(0.03, "npc"), show.legend=TRUE)
g

I tried I tried 
# Get path to temp directory
tmp <- tempdir() 

But did not help.

Would highly appreciate any hint.
Thanks

**Comment by liamxg** [comment]
@koppk @genomicsurveillance can me too, can not find the input data.
