### ISSUE TITLE
Figure scripts not found

### ISSUE THREAD

**Issue by koppk** [genomicsurveillance/Genomic_epidemiology_reveals_how_restriction_measures_shaped_the_SARS-CoV-2_epidemic_in_Brazil#2]
Dear genomicsurveillance team,

first congratulations to your great preprint and publication. I am a virologist with some bioinformatics background but not much experience with R and graphics. I would like to replicate some of your ggplot graphics but struggle to find the scripts for the figures I am most interested in (according to their numbering in the preprint https://pubmed.ncbi.nlm.nih.gov/35378755/ - not in the Nature Microbiology publication):
1C
2B and 2F
3C and 3D

I would be very grateful if you could assist me in finding the responding scripts on github or elsewhere.

Thanks a lot.

Kind regards,
Katharina Kopp

**Comment by liamxg** [comment]
@koppk hope you can get the answer.

**Comment by genomicsurveillance** [comment]
I apologize, but the figures' source codes are unavailable, as the group's partners developed them and are not available for public distribution.

To generate figure 1C you can use this example: https://rpubs.com/thiagovedovatto/secitec2020
To generate figure 2B you can use this example painel D: https://github.com/CERI-KRISP/africa-covid19-genomics/blob/main/Fig1.R
To generate the 2F, 3C and 3D figures. You can use this website as an example:
https://www.data-to-viz.com/graph/sankey.html

**Comment by liamxg** [comment]
thanks.
